# Generated by Django 5.0.6 on 2024-06-09 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('basica', 'Básica'), ('contigua', 'Contigua'), ('extraordinaria', 'Extraordinaria'), ('especial', 'Especial')], max_length=20)),
                ('entidad_federativa', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('seccion', models.CharField(max_length=4)),
                ('distrito_federal', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('siglas', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('archivo_pdf', models.FileField(upload_to='actas/')),
                ('conteo_votos', models.JSONField()),
                ('votos_nulos', models.IntegerField(default=0)),
                ('firmado', models.BooleanField(default=False)),
                ('casilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prep.casilla')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prep.funcionario')),
            ],
        ),
        migrations.AddField(
            model_name='funcionario',
            name='partido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prep.partido'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('funcionario', 'Funcionario de Casilla'), ('votante', 'Votante')], max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='prep_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='prep_user_set', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='funcionario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prep.user'),
        ),
        migrations.CreateModel(
            name='Votante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=20, unique=True)),
                ('ha_votado', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prep.user')),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('acta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prep.acta')),
                ('votante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prep.votante')),
            ],
        ),
    ]
