# Generated by Django 5.0.6 on 2024-06-09 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prep', '0002_partido_total_votos'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('foto', models.ImageField(null=True, upload_to='')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='prep.partido')),
            ],
        ),
    ]
