# Generated by Django 5.0.6 on 2024-06-09 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prep', '0003_partido_logo_candidato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='partido',
        ),
    ]
