# Generated by Django 5.0.6 on 2024-06-09 20:14

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('prep', '0004_remove_funcionario_partido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Administrador', 'Administrador'), ('Funcionario', 'Funcionario'), ('Votante', 'Votante')], max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCasilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='user',
        ),
        migrations.RemoveField(
            model_name='votante',
            name='user',
        ),
        migrations.RemoveField(
            model_name='voto',
            name='votante',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='archivo_pdf',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='casilla',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='conteo_votos',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='firmado',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='votos_nulos',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='partido',
        ),
        migrations.RemoveField(
            model_name='casilla',
            name='distrito_federal',
        ),
        migrations.RemoveField(
            model_name='casilla',
            name='entidad_federativa',
        ),
        migrations.RemoveField(
            model_name='voto',
            name='acta',
        ),
        migrations.RemoveField(
            model_name='voto',
            name='fecha',
        ),
        migrations.AddField(
            model_name='acta',
            name='acta',
            field=models.FileField(blank=True, null=True, upload_to='actas_pdfs/'),
        ),
        migrations.AddField(
            model_name='acta',
            name='candidato_ind',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='acta',
            name='candidato_no_registrado',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='acta',
            name='def_field',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='acta',
            name='estado',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='acta',
            name='firmada',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='acta',
            name='municipio',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='acta',
            name='partido_3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='acta',
            name='voto_nulo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='fullname',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='casilla',
            name='estado',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='casilla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prep.casilla'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='nombre',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='candidato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prep.candidato'),
        ),
        migrations.AddField(
            model_name='voto',
            name='partido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prep.partido'),
        ),
        migrations.AddField(
            model_name='voto',
            name='status',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='acta',
            name='funcionario',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='edad',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='foto',
            field=models.ImageField(upload_to='candidatos_fotos/'),
        ),
        migrations.AlterField(
            model_name='casilla',
            name='municipio',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='casilla',
            name='seccion',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='logo',
            field=models.ImageField(upload_to='partidos_logos/'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='nombre',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='siglas',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('folio', models.CharField(max_length=120, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='customuser_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_set', to='auth.permission', verbose_name='user permissions')),
                ('voto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prep.voto')),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prep.roles')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='casilla',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prep.tipocasilla'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Votante',
        ),
    ]
