# Generated by Django 5.0.6 on 2024-06-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prep', '0006_alter_candidato_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casilla',
            name='tipo',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='casilla',
            name='municipio',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name='TipoCasilla',
        ),
    ]
