# Generated by Django 5.0.6 on 2024-06-10 00:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('prep', '0007_alter_casilla_tipo_alter_casilla_municipio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartidoPolitico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('siglas', models.CharField(blank=True, max_length=10)),
                ('logo', models.ImageField(blank=True, upload_to='partidos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='voto',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='casilla',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='candidato',
        ),
        migrations.RemoveField(
            model_name='voto',
            name='partido',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='acta',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='candidato_ind',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='candidato_no_registrado',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='def_field',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='firmada',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='funcionario',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='partido_3',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='voto_nulo',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='casilla',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='voto',
            name='status',
        ),
        migrations.AddField(
            model_name='acta',
            name='casilla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prep.casilla'),
        ),
        migrations.AddField(
            model_name='acta',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='acta',
            name='pdf',
            field=models.FileField(null=True, upload_to='actas/'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='apellido',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='casilla',
            name='ciudad',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='casilla',
            name='direccion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='casilla',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voto',
            name='candidato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prep.candidato'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='foto',
            field=models.ImageField(blank=True, upload_to='candidatos/'),
        ),
        migrations.AlterField(
            model_name='casilla',
            name='municipio',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='casilla',
            name='seccion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='casilla',
            name='tipo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='partido_politico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prep.partidopolitico'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('funcionario', 'Funcionario'), ('votante', 'Votante')], default='votante', max_length=20)),
                ('groups', models.ManyToManyField(related_name='usuarios', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='usuarios', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='voto',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prep.usuario'),
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
        migrations.DeleteModel(
            name='Partido',
        ),
    ]
