# Generated by Django 5.0.6 on 2024-06-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prep', '0008_partidopolitico_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acta',
            name='votos_candidatos_independientes',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='acta',
            name='votos_no_registrados',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='acta',
            name='votos_nulos',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='acta',
            name='votos_partidos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='edad',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='votos_totales',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='casilla',
            name='votos_totales',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='partidopolitico',
            name='votos_totales',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='voto',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='voto',
            name='tipo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='candidatos/'),
        ),
    ]
