# Generated by Django 5.0.6 on 2024-06-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prep', '0009_acta_votos_candidatos_independientes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidato',
            old_name='foto',
            new_name='foto_principal',
        ),
        migrations.AddField(
            model_name='candidato',
            name='foto_secundaria',
            field=models.ImageField(blank=True, null=True, upload_to='candidatos/'),
        ),
    ]
