# Generated by Django 5.0.6 on 2024-06-10 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prep', '0011_remove_voto_tipo_alter_voto_candidato_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='actas_capturadas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voto',
            name='candidato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prep.candidato'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='voto',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
